import React from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Brain02Icon,
  FileScriptIcon,
  CheckmarkCircle02Icon,
  HelpCircleIcon,
  RefreshIcon,
  FileValidationIcon,
} from "@hugeicons/core-free-icons";

interface AgentThinkingProps {
  agent: string;
  thinking: string;
}

interface AgentPlanProps {
  agent: string;
  plan: {
    steps: Array<{
      id: string;
      type: "web" | "desktop";
      description: string;
      success_criteria: string;
    }>;
  };
}

interface AgentVerifyProps {
  agent: string;
  verification: {
    action_succeeded: boolean;
    error_message?: string;
    confidence: number;
  };
}

interface AgentQuestionProps {
  agent: string;
  question: string;
}

interface AgentRecoveryProps {
  agent: string;
  strategy: {
    strategy: string;
    avoid: string[];
    approach: string;
  };
}

interface AgentReportProps {
  agent: string;
  report: {
    summary: string;
    steps_completed: number;
    total_steps: number;
  };
}

const AGENT_COLORS: Record<string, string> = {
  CLARIFIER: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  ORCHESTRATOR: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  WEB: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  DESKTOP: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  PERCEPTION: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  VERIFIER: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  RECOVERY: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
  REPORTER: "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7",
};

export function AgentThinkingContent({ agent, thinking }: AgentThinkingProps) {
  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7";
  
  return (
    <div className={`mb-2 rounded-md border ${colorClass} p-3 opacity-75`}>
      <div className="flex items-start gap-2">
        <HugeiconsIcon icon={Brain02Icon} className="mt-0.5 h-4 w-4 flex-shrink-0 text-bytebot-bronze-light-12" />
        <div className="flex-1">
          <div className="mb-1 text-xs font-semibold text-bytebot-bronze-light-12">{agent}</div>
          <div className="text-xs italic text-bytebot-bronze-light-12">{thinking}</div>
        </div>
      </div>
    </div>
  );
}

export function AgentPlanContent({ agent, plan }: AgentPlanProps) {
  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-12 bg-bytebot-red-light-1 border-bytebot-bronze-light-6";
  
  // Safety check for plan structure
  if (!plan || !plan.steps || !Array.isArray(plan.steps)) {
    console.error('[AgentPlanContent] Invalid plan structure:', plan);
    return (
      <Card className={`mb-4 w-full shadow-sm overflow-hidden ${colorClass}`}>
        <CardHeader className="pb-3 pt-4 px-4">
          <CardTitle className="text-[13px] font-semibold text-bytebot-bronze-light-12">
            Execution Plan Error
          </CardTitle>
          <CardDescription className="text-[11px] text-bytebot-red-light-11">
            Invalid plan structure received
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }
  
  return (
    <Card className={`mb-4 w-full shadow-sm overflow-hidden ${colorClass}`}>
      <CardHeader className="flex flex-row items-center justify-between pb-3 pt-4 px-4 space-y-0">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-bytebot-bronze-light-3 border border-bytebot-bronze-light-6">
            <HugeiconsIcon icon={FileScriptIcon} className="h-4 w-4 text-bytebot-bronze-light-11" />
          </div>
          <div className="flex flex-col">
            <CardTitle className="text-[13px] font-semibold tracking-tight text-bytebot-bronze-light-12">
              Execution Plan
            </CardTitle>
            <CardDescription className="text-[11px] font-medium text-bytebot-bronze-light-10">
              Generated by {agent} • {plan.steps.length} operations
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="px-4 pb-4 pt-0">
        <div className="relative mt-2 pl-3">
          <div className="absolute left-[15px] top-4 bottom-4 w-px bg-bytebot-bronze-light-5"></div>
          <div className="space-y-4">
            {plan.steps.map((step, index) => (
              <div key={step.id} className="relative pl-7">
                <div className="absolute left-[-4px] top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-bytebot-bronze-light-1 border-2 border-bytebot-bronze-light-7 shadow-sm ring-4 ring-bytebot-red-light-1 z-10">
                  <span className="text-[8px] font-bold text-bytebot-bronze-light-11">
                    {index + 1}
                  </span>
                </div>
                <div className="group rounded-md border border-bytebot-bronze-light-6 bg-bytebot-bronze-light-2/50 backdrop-blur-sm p-3 transition-colors hover:bg-bytebot-bronze-light-3/50 hover:border-bytebot-bronze-light-8 hover:shadow-sm">
                  <div className="flex-1 space-y-1.5 overflow-hidden">
                    <div className="flex items-center gap-2">
                      <span className="inline-flex items-center rounded bg-bytebot-bronze-light-4 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider text-bytebot-bronze-light-11 border border-bytebot-bronze-light-6 shadow-sm">
                        {step.type}
                      </span>
                      <span className="text-[11px] font-semibold font-mono text-bytebot-bronze-light-11 opacity-80">
                        {step.id}
                      </span>
                    </div>
                    <div className="text-[13px] font-medium leading-relaxed text-bytebot-bronze-light-12">
                      {step.description}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export function AgentVerifyContent({ agent, verification }: AgentVerifyProps) {
  const colorClass = "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7";
  
  return (
    <div className={`mb-2 rounded-md border ${colorClass} p-3 opacity-75`}>
      <div className="flex items-start gap-2">
        <HugeiconsIcon icon={CheckmarkCircle02Icon} className="mt-0.5 h-4 w-4 flex-shrink-0 text-bytebot-bronze-light-12" />
        <div className="flex-1">
          <div className="mb-1 text-xs font-semibold text-bytebot-bronze-light-12">
            {agent} - {verification.action_succeeded ? "✓ Success" : "✗ Failed"}
          </div>
          {verification.error_message && (
            <div className="text-xs text-bytebot-bronze-light-12">{verification.error_message}</div>
          )}
          <div className="mt-1 text-xs text-bytebot-bronze-light-12 opacity-60">
            Confidence: {(verification.confidence * 100).toFixed(0)}%
          </div>
        </div>
      </div>
    </div>
  );
}

export function AgentQuestionContent({ agent, question }: AgentQuestionProps) {
  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7";
  
  return (
    <Card className={`mb-4 w-full shadow-sm overflow-hidden ${colorClass}`}>
      <CardHeader className="pb-3 pt-4 px-4">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-bytebot-bronze-light-3 border border-bytebot-bronze-light-6">
            <HugeiconsIcon icon={HelpCircleIcon} className="h-4 w-4 text-bytebot-bronze-light-11" />
          </div>
          <div className="flex flex-col">
            <CardTitle className="text-[13px] font-semibold tracking-tight text-bytebot-bronze-light-12">
              {agent} needs clarification
            </CardTitle>
            <CardDescription className="text-[11px] font-medium text-bytebot-bronze-light-10">
              Please answer to continue
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="px-4 pb-4 pt-0">
        <div className="text-sm text-bytebot-bronze-light-12 leading-relaxed">
          {question}
        </div>
      </CardContent>
    </Card>
  );
}

export function AgentRecoveryContent({ agent, strategy }: AgentRecoveryProps) {
  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7";
  
  return (
    <div className={`mb-2 rounded-md border ${colorClass} p-3`}>
      <div className="flex items-start gap-2">
        <HugeiconsIcon icon={RefreshIcon} className="mt-0.5 h-4 w-4 flex-shrink-0 text-bytebot-bronze-light-12" />
        <div className="flex-1">
          <div className="mb-1 text-xs font-semibold text-bytebot-bronze-light-12">{agent} - Recovery Strategy</div>
          <div className="text-xs text-bytebot-bronze-light-12">
            <div className="mb-1">
              <span className="font-medium">Strategy:</span> {strategy.strategy}
            </div>
            <div className="mb-1">
              <span className="font-medium">Approach:</span> {strategy.approach}
            </div>
            {strategy.avoid.length > 0 && (
              <div>
                <span className="font-medium">Avoid:</span> {strategy.avoid.join(", ")}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export function AgentReportContent({ agent, report }: AgentReportProps) {
  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-11 bg-bytebot-red-light-1 border-bytebot-bronze-light-7";
  
  return (
    <div className={`mb-2 rounded-md border ${colorClass} p-3`}>
      <div className="flex items-start gap-2">
        <HugeiconsIcon icon={FileValidationIcon} className="mt-0.5 h-4 w-4 flex-shrink-0 text-bytebot-bronze-light-12" />
        <div className="flex-1">
          <div className="mb-1 text-xs font-semibold text-bytebot-bronze-light-12">{agent} - Task Report</div>
          <div className="text-xs text-bytebot-bronze-light-12">
            <div className="mb-1">{report.summary}</div>
            <div className="opacity-60">
              Completed {report.steps_completed} of {report.total_steps} steps
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
