"use client";

import React, { useState } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import { FileScriptIcon, PencilEdit02Icon, Tick02Icon, ArrowUp01Icon, ArrowDown01Icon } from "@hugeicons/core-free-icons";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp } from "lucide-react";

interface EditablePlanProps {
  agent: string;
  taskId: string;
  plan: {
    steps: Array<{
      id: string;
      type: "web" | "desktop" | "workflow";
      description: string;
      success_criteria: string;
      workflow_name?: string;
      workflow_vars?: Record<string, any>;
    }>;
  };
  onApprovePlan: (approvedPlan: any[]) => void;
}

interface EditableStep {
  id: string;
  type: "web" | "desktop" | "workflow";
  description: string;
  success_criteria: string;
  workflow_name?: string;
  workflow_vars?: Record<string, any>;
  isEditing: boolean;
}

const AGENT_COLORS: Record<string, string> = {
  ORCHESTRATOR: "text-bytebot-bronze-light-12 bg-bytebot-red-light-1 border-bytebot-bronze-light-6",
};

export function EditablePlanContent({ agent, taskId, plan, onApprovePlan }: EditablePlanProps) {
  const [steps, setSteps] = useState<EditableStep[]>(
    (plan?.steps || []).map((step) => ({ ...step, isEditing: false }))
  );
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);

  const colorClass = AGENT_COLORS[agent] || "text-bytebot-bronze-light-12 bg-bytebot-red-light-1 border-bytebot-bronze-light-6";

  const handleEditStep = (index: number) => {
    setSteps((prev) =>
      prev.map((step, i) => (i === index ? { ...step, isEditing: true } : step))
    );
  };

  const handleSaveStep = (index: number) => {
    setSteps((prev) =>
      prev.map((step, i) => (i === index ? { ...step, isEditing: false } : step))
    );
  };

  const handleDescriptionChange = (index: number, newDescription: string) => {
    setSteps((prev) =>
      prev.map((step, i) => (i === index ? { ...step, description: newDescription } : step))
    );
  };

  const handleApprovePlan = async () => {
    setIsSubmitting(true);
    try {
      const finalizedPlan = steps.map(({ isEditing, ...step }) => step);
      await onApprovePlan(finalizedPlan);
    } catch (error) {
      console.error("Failed to approve plan:", error);
      setIsSubmitting(false);
    }
  };

  return (
    <Card className={`mb-4 w-full shadow-sm ${colorClass}`}>
      <CardHeader className="flex flex-row items-center justify-between pb-3 pt-4 px-4 space-y-0">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-bytebot-bronze-light-3 border border-bytebot-bronze-light-6">
            <HugeiconsIcon icon={FileScriptIcon} className="h-4 w-4 text-bytebot-bronze-light-11" />
          </div>
          <div className="flex flex-col">
            <CardTitle className="text-[13px] font-semibold tracking-tight text-bytebot-bronze-light-12">
              Execution Plan
            </CardTitle>
            <CardDescription className="text-[11px] font-medium text-bytebot-bronze-light-10">
              Generated by {agent} • {steps.length} pending operations
            </CardDescription>
          </div>
        </div>
        <Button
          variant="ghost"
          size="icon"
          className="h-8 w-8 text-bytebot-bronze-light-11 hover:bg-bytebot-bronze-light-4 hover:text-bytebot-bronze-light-12 shrink-0"
          onClick={() => setIsExpanded(!isExpanded)}
        >
          {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </Button>
      </CardHeader>

      {isExpanded && (
        <div className="animate-in slide-in-from-top-2 fade-in duration-200">
          <CardContent className="px-4 pb-4 pt-0">
            <div className="relative mt-2 pl-3">
              {/* Vertical line connecting steps */}
              <div className="absolute left-[15px] top-4 bottom-4 w-px bg-bytebot-bronze-light-5"></div>

              <div className="space-y-4">
                {steps.map((step, index) => (
                  <div key={step.id} className="relative pl-7">
                    {/* Step node */}
                    <div className="absolute left-[-4px] top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-bytebot-bronze-light-1 border-2 border-bytebot-bronze-light-7 shadow-sm ring-4 ring-bytebot-red-light-1 z-10">
                      <span className="text-[8px] font-bold text-bytebot-bronze-light-11">
                        {index + 1}
                      </span>
                    </div>

                    <div className="group rounded-md border border-bytebot-bronze-light-6 bg-bytebot-bronze-light-2/50 backdrop-blur-sm p-3 transition-colors hover:bg-bytebot-bronze-light-3/50 hover:border-bytebot-bronze-light-8 hover:shadow-sm">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 space-y-1.5 overflow-hidden">
                          <div className="flex items-center gap-2">
                            <span className="inline-flex items-center rounded bg-bytebot-bronze-light-4 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider text-bytebot-bronze-light-11 border border-bytebot-bronze-light-6 shadow-sm">
                              {step.type}
                            </span>
                            <span className="text-[11px] font-semibold font-mono text-bytebot-bronze-light-11 opacity-80">
                              {step.id}
                            </span>
                          </div>

                          {step.isEditing ? (
                            <textarea
                              value={step.description}
                              onChange={(e) => handleDescriptionChange(index, e.target.value)}
                              className="mt-2 w-full min-h-[60px] rounded-md border border-bytebot-bronze-light-7 bg-bytebot-bronze-light-1 p-2 text-xs text-bytebot-bronze-light-12 focus:border-bytebot-bronze-light-9 focus:ring-1 focus:ring-bytebot-bronze-light-9 focus:outline-none transition-all shadow-inner"
                              rows={2}
                            />
                          ) : (
                            <div className="text-[13px] font-medium leading-relaxed text-bytebot-bronze-light-12">
                              {step.description}
                            </div>
                          )}

                          <div className="pt-2">
                            <p className="text-[11px] text-bytebot-bronze-light-11 bg-bytebot-bronze-light-3/50 rounded-sm p-1.5 border border-bytebot-bronze-light-5">
                              <span className="font-semibold text-bytebot-bronze-light-11 opacity-90 mr-1.5">Success:</span> 
                              <span className="opacity-80">{step.success_criteria}</span>
                            </p>
                          </div>
                        </div>

                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => (step.isEditing ? handleSaveStep(index) : handleEditStep(index))}
                          className="h-7 w-7 shrink-0 rounded-md border border-transparent bg-transparent text-bytebot-bronze-light-10 opacity-0 transition-all group-hover:opacity-100 hover:bg-bytebot-bronze-light-4 hover:border-bytebot-bronze-light-7 hover:text-bytebot-bronze-light-12"
                          title={step.isEditing ? "Save" : "Edit"}
                        >
                          <HugeiconsIcon
                            icon={step.isEditing ? Tick02Icon : PencilEdit02Icon}
                            className="h-3.5 w-3.5"
                          />
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>

        </div>
      )}

      <CardFooter className="flex items-center justify-between border-t border-bytebot-bronze-light-6 bg-bytebot-bronze-light-2/50 px-4 py-3">
        <p className="text-[11px] font-medium text-bytebot-bronze-light-11 line-clamp-1 mr-2">
          {steps.length > 0 ? "Review and edit before execution." : "Generating plan steps..."}
        </p>
        <div className="flex items-center gap-2 shrink-0">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setIsExpanded(!isExpanded)}
            className="h-7 px-3 text-[11px] font-medium border-bytebot-bronze-light-7 bg-transparent hover:bg-bytebot-bronze-light-4 text-bytebot-bronze-light-11 shadow-sm"
          >
            {isExpanded ? "Collapse" : "Expand"}
          </Button>
          <Button
            size="sm"
            onClick={async () => {
              try {
                await handleApprovePlan();
              } catch (e) {
                console.error("Caught error in onClick:", e);
              }
            }}
            disabled={isSubmitting || steps.length === 0}
            className="h-7 px-3 text-[12px] bg-bytebot-bronze-light-12 flex items-center gap-1.5 font-semibold text-bytebot-red-light-1 hover:bg-bytebot-bronze-light-11 shadow-sm transition-all border border-transparent"
          >
            {isSubmitting ? "Building..." : "Build Plan"}
            {!isSubmitting && <HugeiconsIcon icon={FileScriptIcon} className="h-3.5 w-3.5 ml-0.5 opacity-90" />}
          </Button>
        </div>
      </CardFooter>
    </Card>
  );
}
