## docker-compose file that spins up an aria-desktop container
## and a postgres container. aria-ui and aria-agent are not included
## in this file, and can be run separately using npm, allowing for
## easier local development.

name: aria

services:
  aria-desktop:
    # Build from source
    build:
      context: ../packages/
      dockerfile: ariad/Dockerfile
    # Use pre-built image (commented out - build from source)
    # image: ghcr.io/aria-ai/aria-desktop:edge
    shm_size: "2g"
    container_name: aria-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990" # ariad service & noVNC
    environment:
      - DISPLAY=:0
    networks:
      - aria-network

  postgres:
    image: postgres:16-alpine
    container_name: aria-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ariadb
    networks:
      - aria-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  aria-network:
    driver: bridge

volumes:
  postgres_data:
